### ISSUE TITLE
Document how to build rclone.wasm

### ISSUE THREAD

**Issue by rollbrettler** [sntran/denolcr#1]
Hey,
Could you share how you build the `rclone.wasm` file. Is it essentially this https://github.com/rclone/rclone/blob/master/fs/rc/js/main.go or the main application modified to only include the mentioned backends?
I think its a really interesting approach and Id like to explore it myself a bit but need more backends. Thanks

**Comment by sntran** [comment]
@rollbrettler, you got it. It's basically [fs/rc/js/main.go](https://github.com/rclone/rclone/blob/master/fs/rc/js/main.go), with the addition of some extra backends. Including all the backends make the resulting WASM file too big.

**Comment by rollbrettler** [comment]
Thanks a lot!
